### ISSUE TITLE
Content should have a digest in the (system-)uniqueness constraints

### ISSUE THREAD

**Issue by mdellweg** [pulp/pulp_ansible#1052]
This basically means adding sha256 to the content model and adding it to the uniqueness constraints in the database. At the same time, the uniqueness per repository version should remain the same (e.g. namespace, name, version).

**Comment by netsandbox** [comment]
@mdellweg is it expected that the database migrations maybe take a very long time?
I updated my Pulp 4 hours ago and still see repeated messages:

```
 [ ] 0056_collectionversion_sha256
 [ ] 0057_collectionversion_sha256_migrate
 [ ] 0056_collectionversion_sha256
 [ ] 0057_collectionversion_sha256_migrate
 [ ] 0056_collectionversion_sha256
 [ ] 0057_collectionversion_sha256_migrate
 [ ] 0056_collectionversion_sha256
 [ ] 0057_collectionversion_sha256_migrate
```

**Comment by netsandbox** [comment]
@mdellweg the above mentioned database migrations are running now for 24 hours.
Is this expected or is there something wrong with the migrations?
We are just syncing 13 collections, so there shouldn't be this much data in the database:

```
  - ansible.posix
  - ansible.windows
  - community.crypto
  - community.docker
  - community.general
  - community.hashi_vault
  - community.postgresql
  - community.vmware
  - community.windows
  - fortinet.fortios
  - herve4m.quay
  - microsoft.ad
  - pulp.squeezer
```

**Comment by mdellweg** [comment]
This is most definitely not expected. Do the migrations run anywhere?
The output you posted looks like django planning but then not running the migration for whatever reason.
Can you see it `pulpcore-manager migrate` produces a useful error message?

**Comment by netsandbox** [comment]
```shell
# pulpcore-manager migrate
Operations to perform:
  Apply all migrations: ansible, auth, certguard, container, contenttypes, core, deb, file, gem, maven, ostree, python, rpm, sessions
Running migrations:
  Applying ansible.0056_collectionversion_sha256...Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
  File "/usr/local/lib/python3.9/site-packages/psycopg/cursor.py", line 97, in execute
    raise ex.with_traceback(None)
psycopg.errors.UniqueViolation: could not create unique index "ansible_collectionversion_sha256_a4d120ab_uniq"
DETAIL:  Key (sha256)=() is duplicated.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/pulpcore-manager", line 8, in <module>
    sys.exit(manage())
  File "/usr/local/lib/python3.9/site-packages/pulpcore/app/manage.py", line 11, in manage
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 106, in wrapper
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 356, in handle
    post_migrate_state = executor.migrate(
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 135, in migrate
    state = self._migrate_all_forwards(
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
    state = self.apply_migration(
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 252, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/migration.py", line 132, in apply
    operation.database_forwards(
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/operations/models.py", line 659, in database_forwards
    alter_together(
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/schema.py", line 563, in alter_unique_together
    self.execute(self._create_unique_sql(model, fields))
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/schema.py", line 48, in execute
    return super().execute(sql, None)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/schema.py", line 201, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
  File "/usr/local/lib/python3.9/site-packages/psycopg/cursor.py", line 97, in execute
    raise ex.with_traceback(None)
django.db.utils.IntegrityError: could not create unique index "ansible_collectionversion_sha256_a4d120ab_uniq"
DETAIL:  Key (sha256)=() is duplicated.
```
