### ISSUE TITLE
`logging_cid` is null on dispatching Sync task 

### ISSUE THREAD

**Issue by jerabekjiri** [pulp/pulp_ansible#1323]
**Version**
pulpcore: `3.22.0`
pulp_ansible: `0.17.0`
galaxy_ng: `4.7.0`

**Describe the bug**
Sync task fails with status code 500

```
pulp_1   | pulp [None]: django.request:ERROR: Internal Server Error: /api/automation-hub/pulp/api/v3/repositories/ansible/ansible/3dc6a18f-d1b1-44dd-a6ed-0b00198199b2/sync/
pulp_1   | Traceback (most recent call last):
pulp_1   |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
pulp_1   |     return self.cursor.execute(sql, params)
pulp_1   | psycopg2.errors.NotNullViolation: null value in column "logging_cid" of relation "core_task" violates not-null constraint
pulp_1   | DETAIL:  Failing row contains (f9d4f0b4-16f0-47ff-b55b-db437b3c41cf, 2023-01-16 15:38:50.537753+00, 2023-01-16 15:38:50.537775+00, waiting, pulp_ansible.app.tasks.collections.sync, null, null, null, null, null, null, null, null, {"mirror": false, "optimize": true, "remote_pk": "5421af5a-5d70-..., {/api/automation-hub/pulp/api/v3/repositories/ansible/ansible/3d...).
pulp_1   |
pulp_1   |
pulp_1   | The above exception was the direct cause of the following exception:
pulp_1   |
pulp_1   | Traceback (most recent call last):
pulp_1   |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
pulp_1   |     response = get_response(request)
pulp_1   |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
pulp_1   |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
pulp_1   |   File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
pulp_1   |     return view_func(*args, **kwargs)
pulp_1   |   File "/usr/local/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
pulp_1   |     return self.dispatch(request, *args, **kwargs)
pulp_1   |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
pulp_1   |     response = self.handle_exception(exc)
pulp_1   |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
pulp_1   |     self.raise_uncaught_exception(exc)
pulp_1   |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
pulp_1   |     raise exc
pulp_1   |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
pulp_1   |     response = handler(request, *args, **kwargs)
pulp_1   |   File "/src/pulp_ansible/pulp_ansible/app/viewsets.py", line 296, in sync
pulp_1   |     result = dispatch(
pulp_1   |   File "/src/pulpcore/pulpcore/tasking/tasks.py", line 89, in dispatch
pulp_1   |     task = Task.objects.create(
pulp_1   |   File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
pulp_1   |     return getattr(self.get_queryset(), name)(*args, **kwargs)
pulp_1   |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 453, in create
pulp_1   |     obj.save(force_insert=True, using=self.db)
pulp_1   |   File "/usr/lib64/python3.8/contextlib.py", line 75, in inner
pulp_1   |     return func(*args, **kwds)
pulp_1   |   File "/usr/local/lib/python3.8/site-packages/django_lifecycle/mixins.py", line 169, in save
pulp_1   |     save(*args, **kwargs)
pulp_1   |   File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 739, in save
pulp_1   |     self.save_base(using=using, force_insert=force_insert,
pulp_1   |   File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 776, in save_base
pulp_1   |     updated = self._save_table(
pulp_1   |   File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 881, in _save_table
pulp_1   |     results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
pulp_1   |   File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 919, in _do_insert
pulp_1   |     return manager._insert(
pulp_1   |   File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
pulp_1   |     return getattr(self.get_queryset(), name)(*args, **kwargs)
pulp_1   |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1270, in _insert
pulp_1   |     return query.get_compiler(using=using).execute_sql(returning_fields)
pulp_1   |   File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
pulp_1   |     cursor.execute(sql, params)
pulp_1   |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
pulp_1   |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
pulp_1   |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
pulp_1   |     return executor(sql, params, many, context)
pulp_1   |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
pulp_1   |     return self.cursor.execute(sql, params)
pulp_1   |   File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
pulp_1   |     raise dj_exc_value.with_traceback(traceback) from exc_value
pulp_1   |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
pulp_1   |     return self.cursor.execute(sql, params)
pulp_1   | django.db.utils.IntegrityError: null value in column "logging_cid" of relation "core_task" violates not-null constraint
pulp_1   | DETAIL:  Failing row contains (f9d4f0b4-16f0-47ff-b55b-db437b3c41cf, 2023-01-16 15:38:50.537753+00, 2023-01-16 15:38:50.537775+00, waiting, pulp_ansible.app.tasks.collections.sync, null, null, null, null, null, null, null, null, {"mirror": false, "optimize": true, "remote_pk": "5421af5a-5d70-..., {/api/automation-hub/pulp/api/v3/repositories/ansible/ansible/3d...)
```

**To Reproduce**
Dispatch a sync task: `/pulp/api/v3/repositories/ansible/ansible/<pk>/sync/`

Started happening after https://github.com/pulp/pulpcore/pull/3258

**Additional context**

This happens for syncing container in pulp_container as well.

**Comment by jerabekjiri** [comment]
Closing due to https://github.com/pulp/pulp_ansible/pull/1324#issuecomment-1385577548

@mdellweg thanks for pointing this out and sorry for false alarming issue :)
