### ISSUE TITLE
CI is failing to find RBAC roles

### ISSUE THREAD

**Issue by fao89** [pulp/pulp_ansible#755]
```
E           Traceback (most recent call last):
E             File "/usr/local/lib/python3.8/site-packages/pulpcore/app/role_util.py", line 35, in assign_role
E               role = Role.objects.get(name=rolename)
E             File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
E               return getattr(self.get_queryset(), name)(*args, **kwargs)
E             File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 435, in get
E               raise self.model.DoesNotExist(
E           
E           During handling of the above exception (Role matching query does not exist.), another exception occurred:
E             File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
E               response = get_response(request)
E             File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
E               response = wrapped_callback(request, *callback_args, **callback_kwargs)
E             File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
E               return view_func(*args, **kwargs)
E             File "/usr/local/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
E               return self.dispatch(request, *args, **kwargs)
E             File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
E               response = self.handle_exception(exc)
E             File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
E               self.raise_uncaught_exception(exc)
E             File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
E               raise exc
E             File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
E               response = handler(request, *args, **kwargs)
E             File "/usr/local/lib/python3.8/site-packages/pulp_ansible/app/viewsets.py", line 283, in sync
E               result = dispatch(
E             File "/usr/local/lib/python3.8/site-packages/pulpcore/tasking/tasks.py", line 86, in dispatch
E               task = Task.objects.create(
E             File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
E               return getattr(self.get_queryset(), name)(*args, **kwargs)
E             File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 453, in create
E               obj.save(force_insert=True, using=self.db)
E             File "/usr/lib64/python3.8/contextlib.py", line 75, in inner
E               return func(*args, **kwds)
E             File "/usr/local/lib/python3.8/site-packages/django_lifecycle/mixins.py", line 138, in save
E               self._run_hooked_methods(AFTER_CREATE)
E             File "/usr/local/lib/python3.8/site-packages/django_lifecycle/mixins.py", line 221, in _run_hooked_methods
E               method(self)
E             File "/usr/local/lib/python3.8/site-packages/django_lifecycle/decorators.py", line 69, in func
E               hooked_method(*args, **kwargs)
E             File "/usr/local/lib/python3.8/site-packages/pulpcore/app/models/access_policy.py", line 88, in add_perms
E               self._handle_creation_hooks(access_policy)
E             File "/usr/local/lib/python3.8/site-packages/pulpcore/app/models/access_policy.py", line 96, in _handle_creation_hooks
E               function(**kwargs)
E             File "/usr/local/lib/python3.8/site-packages/pulpcore/app/models/access_policy.py", line 241, in add_roles_for_object_creator
E               assign_role(role, current_user, self)
E             File "/usr/local/lib/python3.8/site-packages/pulpcore/app/role_util.py", line 37, in assign_role
E               raise BadRequest(_("The role '{}' does not exist.").format(rolename))
```

**Comment by mdellweg** [comment]
I think, i need more context.

**Comment by fao89** [comment]
already fixed
