### ISSUE TITLE
Ruby bindings issue: Invalid ENUM value  for class #KeyringEnum (RuntimeError)

### ISSUE THREAD

**Issue by ianballou** [pulp/pulp_ansible#973]
**Version**
Katello 4.5.0+
pulp-ansible                    0.13.0   
pulp-certguard                  1.5.2    
pulp-container                  2.10.3   
pulp-deb                        2.18.0   
pulp-file                       1.10.2   
pulp-ostree                     2.0.0a5  
pulp-python                     3.6.0    
pulp-rpm                        3.17.4   
pulpcore                        3.18.4   
vagrant@centos8-katello-devel ~/foreman

**Describe the bug**
When listing Ansible repository versions in Katello tests, the error below occurs:

```
2022-05-17T17:54:28 [E|bac|] Invalid ENUM value  for class #KeyringEnum (RuntimeError)
 | /home/vagrant/foreman/.vendor/ruby/2.7.0/gems/pulp_ansible_client-0.13.0/lib/pulp_ansible_client/models/keyring_enum.rb:36:in `build_from_hash'
 | /home/vagrant/foreman/.vendor/ruby/2.7.0/gems/pulp_ansible_client-0.13.0/lib/pulp_ansible_client/models/keyring_enum.rb:28:in `build_from_hash'
 | /home/vagrant/foreman/.vendor/ruby/2.7.0/gems/pulp_ansible_client-0.13.0/lib/pulp_ansible_client/models/ansible_ansible_repository_response.rb:278:in `_deserialize'
 | /home/vagrant/foreman/.vendor/ruby/2.7.0/gems/pulp_ansible_client-0.13.0/lib/pulp_ansible_client/models/ansible_ansible_repository_response.rb:234:in `block in build_from_hash'
 | /home/vagrant/foreman/.vendor/ruby/2.7.0/gems/pulp_ansible_client-0.13.0/lib/pulp_ansible_client/models/ansible_ansible_repository_response.rb:226:in `each_pair'
 | /home/vagrant/foreman/.vendor/ruby/2.7.0/gems/pulp_ansible_client-0.13.0/lib/pulp_ansible_client/models/ansible_ansible_repository_response.rb:226:in `build_from_hash'
 | /home/vagrant/foreman/.vendor/ruby/2.7.0/gems/pulp_ansible_client-0.13.0/lib/pulp_ansible_client/models/ansible_ansible_repository_response.rb:218:in `build_from_hash'
 | /home/vagrant/foreman/.vendor/ruby/2.7.0/gems/pulp_ansible_client-0.13.0/lib/pulp_ansible_client/models/paginatedansible_ansible_repository_response_list.rb:187:in `_deserialize'
 | /home/vagrant/foreman/.vendor/ruby/2.7.0/gems/pulp_ansible_client-0.13.0/lib/pulp_ansible_client/models/paginatedansible_ansible_repository_response_list.rb:140:in `block (2 levels) in build_from_hash'
 | /home/vagrant/foreman/.vendor/ruby/2.7.0/gems/pulp_ansible_client-0.13.0/lib/pulp_ansible_client/models/paginatedansible_ansible_repository_response_list.rb:140:in `map'
 | /home/vagrant/foreman/.vendor/ruby/2.7.0/gems/pulp_ansible_client-0.13.0/lib/pulp_ansible_client/models/paginatedansible_ansible_repository_response_list.rb:140:in `block in build_from_hash'
 | /home/vagrant/foreman/.vendor/ruby/2.7.0/gems/pulp_ansible_client-0.13.0/lib/pulp_ansible_client/models/paginatedansible_ansible_repository_response_list.rb:135:in `each_pair'
 | /home/vagrant/foreman/.vendor/ruby/2.7.0/gems/pulp_ansible_client-0.13.0/lib/pulp_ansible_client/models/paginatedansible_ansible_repository_response_list.rb:135:in `build_from_hash'
 | /home/vagrant/foreman/.vendor/ruby/2.7.0/gems/pulp_ansible_client-0.13.0/lib/pulp_ansible_client/models/paginatedansible_ansible_repository_response_list.rb:127:in `build_from_hash'
 | /home/vagrant/foreman/.vendor/ruby/2.7.0/gems/pulp_ansible_client-0.13.0/lib/pulp_ansible_client/api_client.rb:255:in `convert_to_type'
 | /home/vagrant/foreman/.vendor/ruby/2.7.0/gems/pulp_ansible_client-0.13.0/lib/pulp_ansible_client/api_client.rb:216:in `deserialize'
 | /home/vagrant/foreman/.vendor/ruby/2.7.0/gems/pulp_ansible_client-0.13.0/lib/pulp_ansible_client/api_client.rb:94:in `call_api'
 | /home/vagrant/foreman/.vendor/ruby/2.7.0/gems/pulp_ansible_client-0.13.0/lib/pulp_ansible_client/api/repositories_ansible_api.rb:230:in `list_with_http_info'
 | /home/vagrant/foreman/.vendor/ruby/2.7.0/gems/pulp_ansible_client-0.13.0/lib/pulp_ansible_client/api/repositories_ansible_api.rb:164:in `list'
 | /home/vagrant/katello/app/services/katello/pulp3/api/core.rb:211:in `block in list_all'
 | /home/vagrant/katello/app/services/katello/pulp3/api/core.rb:237:in `block in fetch_from_list'
 | /home/vagrant/katello/app/services/katello/pulp3/api/core.rb:232:in `loop'
 | /home/vagrant/katello/app/services/katello/pulp3/api/core.rb:232:in `fetch_from_list'
 | /home/vagrant/katello/app/services/katello/pulp3/api/core.rb:210:in `list_all'
 | /home/vagrant/katello/app/services/katello/pulp3/api/core.rb:175:in `repository_versions'
 | /home/vagrant/katello/app/services/katello/pulp3/smart_proxy_repository.rb:59:in `block in orphan_repository_versions'
```

**To Reproduce**
List all ansible repository versions via the Ruby bindings

**Expected behavior**
List Ansible repo versions

**Additional context**
I hit this when running tests after upgrading to Pulpcore 3.18.

**Comment by ianballou** [comment]
Looks like it also happens when trying to create an Ansible repo:

```2022-05-17T17:50:05 [E|bac|] Invalid ENUM value  for class #KeyringEnum (RuntimeError)
 | /home/vagrant/foreman/.vendor/ruby/2.7.0/gems/pulp_ansible_client-0.13.0/lib/pulp_ansible_client/models/keyring_enum.rb:36:in `build_from_hash'
 | /home/vagrant/foreman/.vendor/ruby/2.7.0/gems/pulp_ansible_client-0.13.0/lib/pulp_ansible_client/models/keyring_enum.rb:28:in `build_from_hash'
 | /home/vagrant/foreman/.vendor/ruby/2.7.0/gems/pulp_ansible_client-0.13.0/lib/pulp_ansible_client/models/ansible_ansible_repository_response.rb:278:in `_deserialize'
 | /home/vagrant/foreman/.vendor/ruby/2.7.0/gems/pulp_ansible_client-0.13.0/lib/pulp_ansible_client/models/ansible_ansible_repository_response.rb:234:in `block in build_from_hash'
 | /home/vagrant/foreman/.vendor/ruby/2.7.0/gems/pulp_ansible_client-0.13.0/lib/pulp_ansible_client/models/ansible_ansible_repository_response.rb:226:in `each_pair'
 | /home/vagrant/foreman/.vendor/ruby/2.7.0/gems/pulp_ansible_client-0.13.0/lib/pulp_ansible_client/models/ansible_ansible_repository_response.rb:226:in `build_from_hash'
 | /home/vagrant/foreman/.vendor/ruby/2.7.0/gems/pulp_ansible_client-0.13.0/lib/pulp_ansible_client/models/ansible_ansible_repository_response.rb:218:in `build_from_hash'
 | /home/vagrant/foreman/.vendor/ruby/2.7.0/gems/pulp_ansible_client-0.13.0/lib/pulp_ansible_client/api_client.rb:255:in `convert_to_type'
 | /home/vagrant/foreman/.vendor/ruby/2.7.0/gems/pulp_ansible_client-0.13.0/lib/pulp_ansible_client/api_client.rb:216:in `deserialize'
 | /home/vagrant/foreman/.vendor/ruby/2.7.0/gems/pulp_ansible_client-0.13.0/lib/pulp_ansible_client/api_client.rb:94:in `call_api'
 | /home/vagrant/foreman/.vendor/ruby/2.7.0/gems/pulp_ansible_client-0.13.0/lib/pulp_ansible_client/api/repositories_ansible_api.rb:79:in `create_with_http_info'
 | /home/vagrant/foreman/.vendor/ruby/2.7.0/gems/pulp_ansible_client-0.13.0/lib/pulp_ansible_client/api/repositories_ansible_api.rb:28:in `create'
 | /home/vagrant/katello/app/services/katello/pulp3/repository.rb:165:in `create'

```
